//
// Milkyway Hierarchical Verilog Dump:
// Generated on 05/07/2021 at 19:51:13
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :control_pad.mw
// Cell Name    :route
// Hierarchy delimiter:'/'
// Write Command : write_verilog ../output/control_pad_final.v -no_physical_only_cells  
//	-no_tap_cells -no_unconnected_cells
//


module control_pad (rd , zero , clk , rst_ , opcode , sel , data_e , 
    halt , inc_pc , ld_pc , ld_ac , ld_ir , wr );
output rd ;
input  zero ;
input  clk ;
input  rst_ ;
input  [2:0] opcode ;
output sel ;
output data_e ;
output halt ;
output inc_pc ;
output ld_pc ;
output ld_ac ;
output ld_ir ;
output wr ;


wire [2:0] opcode_pad ;

DLY2X4 CTS_clk_CTO_delay3 (.Y ( CTS_clk_CTO_delay31 ) , .A ( clk_pad ) ) ;
PI i_rst (.PAD ( rst_ ) , .C ( rst_pad ) ) ;
PI i_clk (.PAD ( clk ) , .C ( clk_pad ) ) ;
PI i_zero (.PAD ( zero ) , .C ( zero_pad ) ) ;
PI i_opcode_0 (.PAD ( opcode[0] ) , .C ( opcode_pad[0] ) ) ;
PI i_opcode_1 (.PAD ( opcode[1] ) , .C ( opcode_pad[1] ) ) ;
PI i_opcode_2 (.PAD ( opcode[2] ) , .C ( opcode_pad[2] ) ) ;
PO8 i_rd (.PAD ( rd ) , .I ( rd_pad ) ) ;
PO8 i_wr (.PAD ( wr ) , .I ( wr_pad ) ) ;
PO8 i_ld_ir (.PAD ( ld_ir ) , .I ( n2 ) ) ;
PO8 i_ld_ac (.PAD ( ld_ac ) , .I ( ld_ac_pad ) ) ;
PO8 i_ld_pc (.PAD ( ld_pc ) , .I ( ld_pc_pad ) ) ;
PO8 i_inc_pc (.PAD ( inc_pc ) , .I ( inc_pc_pad ) ) ;
PO8 i_halt (.PAD ( halt ) , .I ( halt_pad ) ) ;
PO8 i_data_e (.PAD ( data_e ) , .I ( data_e_pad ) ) ;
PO8 i_sel (.PAD ( sel ) , .I ( sel_pad ) ) ;
DFFRX1 i_control_state_reg_2_ (.RN ( rst_pad ) , .Q ( i_control_state_2_ ) 
    , .QN ( n19 ) , .D ( i_control_N14 ) , .CK ( CTS_clk_CTO_delay31 ) ) ;
DFFRXL i_control_state_reg_1_ (.RN ( rst_pad ) , .Q ( n18 ) , .QN ( n4 ) 
    , .D ( sel_pad ) , .CK ( CTS_clk_CTO_delay31 ) ) ;
DFFRX1 i_control_state_reg_0_ (.RN ( rst_pad ) , .QN ( n3 ) 
    , .D ( i_control_N21 ) , .CK ( CTS_clk_CTO_delay31 ) ) ;
NOR2X2 U3 (.Y ( wr_pad ) , .A ( opcode_pad[0] ) , .B ( n5 ) ) ;
NOR2X2 U20 (.Y ( data_e_pad ) , .A ( n8 ) , .B ( n9 ) ) ;
AND2X2 U8 (.Y ( ld_ac_pad ) , .B ( n8 ) , .A ( n11 ) ) ;
NOR3BX2 U17 (.Y ( halt_pad ) , .AN ( n14 ) , .B ( opcode_pad[0] ) , .C ( n12 ) ) ;
INVX1 U1 (.Y ( n1 ) , .A ( opcode_pad[0] ) ) ;
NOR2X1 U19 (.Y ( n14 ) , .A ( opcode_pad[1] ) , .B ( opcode_pad[2] ) ) ;
NAND3X1 U11 (.Y ( n5 ) , .A ( n11 ) , .B ( opcode_pad[1] ) 
    , .C ( opcode_pad[2] ) ) ;
AOI2BB2X1 U23 (.A1N ( opcode_pad[2] ) , .Y ( n8 ) , .A0N ( opcode_pad[1] ) 
    , .B1 ( opcode_pad[2] ) , .B0 ( opcode_pad[1] ) ) ;
NOR2BX2 U24 (.Y ( sel_pad ) , .AN ( n9 ) , .B ( n20 ) ) ;
CLKINVX2 U25 (.Y ( n2 ) , .A ( n7 ) ) ;
NAND4BX1 U26 (.Y ( n15 ) , .C ( opcode_pad[0] ) , .AN ( n9 ) , .B ( zero_pad ) 
    , .D ( n14 ) ) ;
OAI211X2 U27 (.A1 ( n1 ) , .A0 ( n5 ) , .C0 ( n15 ) , .Y ( inc_pc_pad ) 
    , .B0 ( n12 ) ) ;
NAND3XL U28 (.Y ( n16 ) , .A ( opcode_pad[0] ) , .B ( opcode_pad[2] ) 
    , .C ( opcode_pad[1] ) ) ;
NOR2X2 U29 (.Y ( ld_pc_pad ) , .A ( n9 ) , .B ( n16 ) ) ;
OAI211X1 U30 (.A1 ( i_control_state_2_ ) , .A0 ( n3 ) , .C0 ( n4 ) , .Y ( n17 ) 
    , .B0 ( n8 ) ) ;
OAI211X2 U31 (.A1 ( n4 ) , .A0 ( i_control_state_2_ ) , .C0 ( n17 ) 
    , .Y ( rd_pad ) , .B0 ( n7 ) ) ;
NOR2X1 U32 (.Y ( n11 ) , .A ( i_control_state_2_ ) , .B ( n9 ) ) ;
NAND2X1 U33 (.Y ( n12 ) , .B ( n18 ) , .A ( n20 ) ) ;
NAND2BXL U34 (.Y ( i_control_N14 ) , .B ( n7 ) , .AN ( n20 ) ) ;
NAND2XL U35 (.Y ( n7 ) , .B ( n18 ) , .A ( n3 ) ) ;
NOR2XL U36 (.Y ( n20 ) , .A ( n3 ) , .B ( n19 ) ) ;
NAND2X1 U37 (.Y ( n9 ) , .B ( n3 ) , .A ( n4 ) ) ;
OAI22XL U38 (.A1 ( n19 ) , .A0 ( n4 ) , .Y ( i_control_N21 ) 
    , .B1 ( i_control_state_2_ ) , .B0 ( n18 ) ) ;
endmodule


